### ISSUE TITLE
No poster images visible when on https

### ISSUE THREAD

**Issue by wookash** [jonkristian/mediatracker-ha-card#1]
I've set up media tracker app in docker, imported watchlist from trakt.tv, all good. I've set up your integration in Home Assistant, integration shows entities and entries, all good. But now I don't see the poster images:

![image](https://github.com/jonkristian/mediatracker-ha-card/assets/222462/449a6411-91dc-401c-93e5-5ef2560b61f6)

When accessing HA from local IP address images load fine, but the poster images don't load when HA url is https, so it's to do with not loading media tracker poster images via HTTPS. How to fix this?

**Comment by wookash** [comment]
Hello. Is there any ETA on this fix, please?

**Comment by jonkristian** [comment]
Sorry about that, been a little hectic lately. I will take a look at this during the next couple of days. UPDATE: It's gonna a little longer, but think I can manage this week :)

**Comment by wookash** [comment]
Can I help in any way?

**Comment by jonkristian** [comment]
@wookash : Can you test the code from the master branch? If you're using HACS you can do it by enabling beta on re-install.

**Comment by wookash** [comment]
> @wookash : Can you test the code from the master branch? If you're using HACS you can do it by enabling beta on re-install.

Nope, still the same I’m afraid. Works in companion app via internal url, doesn’t work when connected via external url. Desktop app doesn’t display images either as I’m connecting via ssl and reverse proxy.

**Comment by jonkristian** [comment]
How have you set up mediatracker? Stupid question maybe, but is your MT instance accessible externally? Can you inspect the broken image in the browser and see what the url is? I tested master branch and was able to load images just fine now, they were also broken for me via nabu casa.

**Comment by wookash** [comment]
> How have you set up mediatracker? Stupid question maybe, but is your MT instance accessible externally? Can you inspect the broken image in the browser and see what the url is? I tested master branch and was able to load images just fine now, they were also broken for me via nabu casa.

mediatracker is set up in the docker container and its not exposed externally, my HA instance is. I'd prefer to keep it this way. I thought that there may be a way to pull the images via API, similarly to the 'competing' solution (trakt integration).. ?

**Comment by jonkristian** [comment]
I understand, I will take a look at how we can achieve that. 

EDIT: Looks like there's a `externalPosterUrl` and `externalBackdropUrl` available via the API. I will see if I can set something up for your use-case so you can switch these on.

**Comment by jonkristian** [comment]
@wookash Please try the latest versions of the integration and this card, it should hopefully fix your issue. When you edit your card you should have a new option to load media externally. Please let me know how it works out.

**Comment by wookash** [comment]
@jonkristian I confirm it is working in the latest version. Awesome, thank you!
